### ISSUE TITLE
Copy Paste throwing error

### ISSUE THREAD

**Issue by nnuzaba** [nn3un/Show-Your-Work#5]
```
java.lang.Throwable: cannot share data context between Swing events; initial event count = 4899; current event count = 4903
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:351)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:59)
	at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:178)
	at CopyPasteListener.afterActionPerformed(CopyPasteListener.java:43)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireAfterActionPerformed(ActionManagerImpl.java:1210)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)``
```

**Comment by jzyhywxz** [comment]
@nn3un hi, I'm also encounting the same problem when I create my plugin. Have you already solved this problem? If you did, could you please tell me your solution? Thanks.

**Comment by nnuzaba** [comment]
Sorry it's been a long time since I worked on this project. I don't think I did. There is a commit on Dec 25th though, so maybe you can check that to see if there's anything useful.

**Comment by jzyhywxz** [comment]
@nn3un Thanks, I'll just do it.
